// Basic smoke test generated by CRA to confirm the App renders.
import { render, screen } from '@testing-library/react';
import App from './App';

test('renders Rental Haven welcome text', () => {
  render(<App />);
  const welcomeText = screen.getByText(/welcome to rental haven/i);
  expect(welcomeText).toBeInTheDocument();
});